# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  issues:
    types: [opened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Checkout javadiff
        uses: actions/checkout@v2
        with:
          repository: amir9979/javadiff
          path: ./javadiff
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
          pip install gitpython
          pip install jira
          pip install termcolor 
          pip install openpyxl  
          pip install javalang
          pip install pathlib
          pip install junitparser

      - name: javadiff_install
        run: python ./javadiff/setup.py install
      
      - name: echo
        run: echo 123 > repository_data\r.txt

      - name: execute
        run: python extract_all.py ${{github.event.issue.title}} ${{github.event.issue.body}}

      - name: Upload גשאש
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: data
          # A file, directory or wildcard pattern that describes what to upload
          path: data
